import { Doctor, Patient, Appointment, Prescription, VisitHistory, Bed, RosterEntry, Notification, User } from "@/types";

export const doctors: Doctor[] = [
  {
    id: "doc-001",
    name: "Dr. Sarah Mitchell",
    specialization: "Cardiology",
    branch: "Main Branch",
    experience: 15,
    opdTimings: "Mon-Fri: 9:00 AM - 1:00 PM",
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop",
    email: "sarah.mitchell@mediflow.com",
    phone: "+1 (555) 123-4567",
    about: "Dr. Mitchell is a board-certified cardiologist with over 15 years of experience in interventional cardiology and heart failure management.",
    rating: 4.9,
    patientsCount: 1200,
    isAvailable: true,
  },
  {
    id: "doc-002",
    name: "Dr. James Chen",
    specialization: "Neurology",
    branch: "Main Branch",
    experience: 12,
    opdTimings: "Mon-Wed-Fri: 2:00 PM - 6:00 PM",
    photo: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop",
    email: "james.chen@mediflow.com",
    phone: "+1 (555) 234-5678",
    about: "Specializing in neurodegenerative diseases and stroke rehabilitation with advanced training from Johns Hopkins.",
    rating: 4.8,
    patientsCount: 950,
    isAvailable: true,
  },
  {
    id: "doc-003",
    name: "Dr. Emily Rodriguez",
    specialization: "Pediatrics",
    branch: "North Branch",
    experience: 10,
    opdTimings: "Tue-Thu-Sat: 10:00 AM - 2:00 PM",
    photo: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=400&fit=crop",
    email: "emily.rodriguez@mediflow.com",
    phone: "+1 (555) 345-6789",
    about: "Dedicated pediatrician focused on preventive care, developmental pediatrics, and childhood immunizations.",
    rating: 4.9,
    patientsCount: 1500,
    isAvailable: true,
  },
  {
    id: "doc-004",
    name: "Dr. Michael Thompson",
    specialization: "Orthopedics",
    branch: "South Branch",
    experience: 18,
    opdTimings: "Mon-Fri: 3:00 PM - 7:00 PM",
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop",
    email: "michael.thompson@mediflow.com",
    phone: "+1 (555) 456-7890",
    about: "Expert in joint replacement surgery, sports medicine, and minimally invasive orthopedic procedures.",
    rating: 4.7,
    patientsCount: 800,
    isAvailable: true,
  },
  {
    id: "doc-005",
    name: "Dr. Aisha Patel",
    specialization: "Dermatology",
    branch: "Main Branch",
    experience: 8,
    opdTimings: "Mon-Wed: 11:00 AM - 3:00 PM",
    photo: "https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=400&h=400&fit=crop",
    email: "aisha.patel@mediflow.com",
    phone: "+1 (555) 567-8901",
    about: "Cosmetic and medical dermatologist specializing in skin cancer detection, acne treatment, and laser therapy.",
    rating: 4.8,
    patientsCount: 600,
    isAvailable: true,
  },
  {
    id: "doc-006",
    name: "Dr. Robert Kim",
    specialization: "Oncology",
    branch: "North Branch",
    experience: 20,
    opdTimings: "Tue-Thu: 9:00 AM - 1:00 PM",
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=400&fit=crop",
    email: "robert.kim@mediflow.com",
    phone: "+1 (555) 678-9012",
    about: "Leading oncologist with expertise in targeted therapy, immunotherapy, and precision medicine approaches.",
    rating: 4.9,
    patientsCount: 700,
    isAvailable: true,
  },
];

export const patients: Patient[] = [
  {
    id: "pat-001",
    name: "John Anderson",
    email: "john.anderson@email.com",
    phone: "+1 (555) 111-2222",
    bloodType: "O+",
    admissionStatus: "Admitted",
    branch: "Main Branch",
    ward: "Cardiac Ward A",
    bedNumber: "A-105",
    age: 58,
    gender: "Male",
    address: "123 Oak Street, Springfield",
    emergencyContact: "+1 (555) 111-3333 (Wife)",
    assignedDoctorId: "doc-001",
  },
  {
    id: "pat-002",
    name: "Maria Garcia",
    email: "maria.garcia@email.com",
    phone: "+1 (555) 222-3333",
    bloodType: "A-",
    admissionStatus: "Outpatient",
    branch: "Main Branch",
    age: 34,
    gender: "Female",
    address: "456 Maple Avenue, Springfield",
    emergencyContact: "+1 (555) 222-4444 (Mother)",
    assignedDoctorId: "doc-003",
  },
  {
    id: "pat-003",
    name: "David Wilson",
    email: "david.wilson@email.com",
    phone: "+1 (555) 333-4444",
    bloodType: "B+",
    admissionStatus: "Admitted",
    branch: "North Branch",
    ward: "Neuro Ward B",
    bedNumber: "B-210",
    age: 67,
    gender: "Male",
    address: "789 Pine Road, Springfield",
    emergencyContact: "+1 (555) 333-5555 (Son)",
    assignedDoctorId: "doc-002",
  },
  {
    id: "pat-004",
    name: "Lisa Brown",
    email: "lisa.brown@email.com",
    phone: "+1 (555) 444-5555",
    bloodType: "AB+",
    admissionStatus: "Outpatient",
    branch: "South Branch",
    age: 29,
    gender: "Female",
    address: "321 Elm Drive, Springfield",
    emergencyContact: "+1 (555) 444-6666 (Husband)",
    assignedDoctorId: "doc-005",
  },
  {
    id: "pat-005",
    name: "James Taylor",
    email: "james.taylor@email.com",
    phone: "+1 (555) 555-6666",
    bloodType: "O-",
    admissionStatus: "Admitted",
    branch: "Main Branch",
    ward: "Ortho Ward C",
    bedNumber: "C-305",
    age: 45,
    gender: "Male",
    address: "654 Birch Lane, Springfield",
    emergencyContact: "+1 (555) 555-7777 (Brother)",
    assignedDoctorId: "doc-004",
  },
];

export const appointments: Appointment[] = [
  {
    id: "apt-001",
    patientId: "pat-002",
    doctorId: "doc-003",
    date: "2024-09-05",
    timeSlot: "10:30 AM",
    status: "Confirmed",
    type: "Routine Checkup",
    notes: "Annual pediatric wellness visit",
    createdAt: "2024-09-01T10:00:00Z",
  },
  {
    id: "apt-002",
    patientId: "pat-004",
    doctorId: "doc-005",
    date: "2024-09-06",
    timeSlot: "11:00 AM",
    status: "Pending",
    type: "Dermatology Consultation",
    notes: "Follow-up for skin rash treatment",
    createdAt: "2024-09-01T11:00:00Z",
  },
  {
    id: "apt-003",
    patientId: "pat-001",
    doctorId: "doc-001",
    date: "2024-09-03",
    timeSlot: "9:30 AM",
    status: "Completed",
    type: "Cardiac Review",
    notes: "Post-surgery follow-up",
    createdAt: "2024-08-28T09:00:00Z",
  },
  {
    id: "apt-004",
    patientId: "pat-003",
    doctorId: "doc-002",
    date: "2024-09-07",
    timeSlot: "2:00 PM",
    status: "Confirmed",
    type: "Neurology Assessment",
    notes: "Cognitive function evaluation",
    createdAt: "2024-09-01T12:00:00Z",
  },
];

export const prescriptions: Prescription[] = [
  {
    id: "rx-001",
    patientId: "pat-001",
    doctorId: "doc-001",
    diagnosis: "Post-CABG Recovery",
    notes: "Continue cardiac rehabilitation. Monitor BP daily.",
    date: "2024-09-01",
    validUntil: "2024-10-01",
    medicines: [
      { name: "Atorvastatin", dosage: "40mg", frequency: "Once daily", timing: ["8:00 AM"], duration: "30 days" },
      { name: "Metoprolol", dosage: "50mg", frequency: "Twice daily", timing: ["8:00 AM", "8:00 PM"], duration: "30 days" },
      { name: "Aspirin", dosage: "81mg", frequency: "Once daily", timing: ["8:00 AM"], duration: "30 days" },
    ],
  },
  {
    id: "rx-002",
    patientId: "pat-003",
    doctorId: "doc-002",
    diagnosis: "Ischemic Stroke Recovery",
    notes: "Physical therapy 3x/week. Speech therapy as needed.",
    date: "2024-09-01",
    validUntil: "2024-10-01",
    medicines: [
      { name: "Clopidogrel", dosage: "75mg", frequency: "Once daily", timing: ["9:00 AM"], duration: "30 days" },
      { name: "Simvastatin", dosage: "20mg", frequency: "Once daily", timing: ["9:00 PM"], duration: "30 days" },
    ],
  },
  {
    id: "rx-003",
    patientId: "pat-005",
    doctorId: "doc-004",
    diagnosis: "Post-ACL Reconstruction",
    notes: "Weight-bearing as tolerated. PT exercises daily.",
    date: "2024-09-01",
    validUntil: "2024-09-15",
    medicines: [
      { name: "Ibuprofen", dosage: "600mg", frequency: "Every 8 hours", timing: ["8:00 AM", "4:00 PM", "12:00 AM"], duration: "14 days" },
      { name: "Cephalexin", dosage: "500mg", frequency: "Four times daily", timing: ["8:00 AM", "12:00 PM", "4:00 PM", "8:00 PM"], duration: "7 days" },
    ],
  },
];

export const visitHistories: VisitHistory[] = [
  {
    id: "vis-001",
    patientId: "pat-001",
    date: "2024-08-15",
    doctorId: "doc-001",
    diagnosis: "Coronary Artery Disease - Triple Vessel",
    symptoms: ["Chest pain", "Shortness of breath", "Fatigue"],
    notes: "Patient underwent successful CABG. Recovery progressing well.",
  },
  {
    id: "vis-002",
    patientId: "pat-001",
    date: "2024-08-01",
    doctorId: "doc-001",
    diagnosis: "Pre-operative Assessment",
    symptoms: ["Chest tightness", "Palpitations"],
    notes: "Angiography confirmed triple vessel disease. Scheduled for CABG.",
  },
  {
    id: "vis-003",
    patientId: "pat-003",
    date: "2024-08-20",
    doctorId: "doc-002",
    diagnosis: "Acute Ischemic Stroke",
    symptoms: ["Left-sided weakness", "Slurred speech", "Facial droop"],
    notes: "tPA administered within window. Admitted for monitoring and rehab.",
  },
];

export const beds: Bed[] = [
  { id: "bed-001", ward: "Cardiac Ward A", bedNumber: "A-101", status: "Occupied", patientId: "pat-001", branch: "Main Branch" },
  { id: "bed-002", ward: "Cardiac Ward A", bedNumber: "A-102", status: "Available", branch: "Main Branch" },
  { id: "bed-003", ward: "Cardiac Ward A", bedNumber: "A-103", status: "Available", branch: "Main Branch" },
  { id: "bed-004", ward: "Cardiac Ward A", bedNumber: "A-104", status: "Maintenance", branch: "Main Branch" },
  { id: "bed-005", ward: "Cardiac Ward A", bedNumber: "A-105", status: "Occupied", patientId: "pat-001", branch: "Main Branch" },
  { id: "bed-006", ward: "Neuro Ward B", bedNumber: "B-201", status: "Available", branch: "North Branch" },
  { id: "bed-007", ward: "Neuro Ward B", bedNumber: "B-202", status: "Available", branch: "North Branch" },
  { id: "bed-008", ward: "Neuro Ward B", bedNumber: "B-210", status: "Occupied", patientId: "pat-003", branch: "North Branch" },
  { id: "bed-009", ward: "Ortho Ward C", bedNumber: "C-301", status: "Available", branch: "South Branch" },
  { id: "bed-010", ward: "Ortho Ward C", bedNumber: "C-305", status: "Occupied", patientId: "pat-005", branch: "South Branch" },
];

export const roster: RosterEntry[] = [
  {
    id: "ros-001",
    doctorId: "doc-001",
    date: "2024-09-02",
    shift: "Morning",
    startTime: "9:00 AM",
    endTime: "1:00 PM",
    type: "OPD",
    room: "Room 101",
    notes: "General cardiology consultations",
  },
  {
    id: "ros-002",
    doctorId: "doc-001",
    date: "2024-09-02",
    shift: "Morning",
    startTime: "1:00 PM",
    endTime: "2:00 PM",
    type: "Break",
  },
  {
    id: "ros-003",
    doctorId: "doc-001",
    date: "2024-09-02",
    shift: "Evening",
    startTime: "2:00 PM",
    endTime: "4:00 PM",
    type: "Surgery",
    room: "OR-3",
    notes: "Scheduled CABG for patient John Anderson",
  },
  {
    id: "ros-004",
    doctorId: "doc-002",
    date: "2024-09-02",
    shift: "Morning",
    startTime: "9:00 AM",
    endTime: "12:00 PM",
    type: "Ward Round",
    notes: "Neuro Ward B patient rounds",
  },
  {
    id: "ros-005",
    doctorId: "doc-002",
    date: "2024-09-02",
    shift: "Evening",
    startTime: "2:00 PM",
    endTime: "6:00 PM",
    type: "OPD",
    room: "Room 205",
  },
];

export const notifications: Notification[] = [
  {
    id: "notif-001",
    userId: "pat-001",
    title: "Medication Reminder",
    message: "Time to take Atorvastatin 40mg",
    type: "warning",
    timestamp: "2024-09-01T08:00:00Z",
    read: false,
  },
  {
    id: "notif-002",
    userId: "pat-001",
    title: "Appointment Confirmed",
    message: "Your cardiac review with Dr. Mitchell is confirmed for Sep 3, 9:30 AM",
    type: "success",
    timestamp: "2024-08-28T09:00:00Z",
    read: true,
  },
  {
    id: "notif-003",
    userId: "doc-001",
    title: "New Patient Assignment",
    message: "Patient John Anderson has been assigned to you for post-CABG care",
    type: "info",
    timestamp: "2024-08-15T14:00:00Z",
    read: false,
  },
];

export const users: User[] = [
  { id: "user-001", name: "John Anderson", email: "john.anderson@email.com", role: "patient", phone: "+1 (555) 111-2222", hospitalId: "HOSP-2024-001" },
  { id: "user-002", name: "Dr. Sarah Mitchell", email: "sarah.mitchell@mediflow.com", role: "doctor", phone: "+1 (555) 123-4567", hospitalId: "HOSP-DOC-001" },
  { id: "user-003", name: "Admin User", email: "admin@mediflow.com", role: "receptionist", phone: "+1 (555) 999-0000", hospitalId: "HOSP-ADM-001" },
];
